// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// corr_as
Eigen::VectorXd corr_as(Eigen::Map<Eigen::MatrixXd> SgA, Eigen::Map<Eigen::MatrixXd> SgB, Eigen::Map<Eigen::MatrixXd> LmA, Eigen::Map<Eigen::MatrixXd> LmB);
RcppExport SEXP _corrad_corr_as(SEXP SgASEXP, SEXP SgBSEXP, SEXP LmASEXP, SEXP LmBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type SgA(SgASEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type SgB(SgBSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type LmA(LmASEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type LmB(LmBSEXP);
    rcpp_result_gen = Rcpp::wrap(corr_as(SgA, SgB, LmA, LmB));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_corrad_corr_as", (DL_FUNC) &_corrad_corr_as, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_corrad(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
