# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculating correlation anomaly score
#'   based on Kullback-Leibler divergence.
#'
#' @useDynLib corrad
#' @importFrom Rcpp evalCpp
#'
#' @param SgA,SgB estimated (sparse) covariance matrix
#' @param LmA,LmB estimated (sparse) precision matrix
#' @export
NULL

corr_as <- function(SgA, SgB, LmA, LmB) {
    .Call('_corrad_corr_as', PACKAGE = 'corrad', SgA, SgB, LmA, LmB)
}

