# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculating correlation anomaly score using KL divergence
#'
#' @param SgA,SgB covariance matrix of reference or test data.
#' @param LmA,LmB inverse covariance matrix (i.e. precision matrix)
#'   of reference or test data.
#' @export
NULL

corr_as <- function(SgA, SgB, LmA, LmB) {
    .Call(`_corrad_corr_as`, SgA, SgB, LmA, LmB)
}

